Test Cases Added
talgalili/dendextend pull request #130
Opened 2024-10-30 18:51 UTC by alecbuetow

Can we keep this pull request open for a few hours? I think Github is registering the merge as one commit on the upstream repo but still tracking every individual commit in my forked repo, which is forcing me to re-sync for every merge. I want to check if committing directly to the PR resolves this

2024-10-30 19:42 UTC, talgalili commented
Sure

On Wed, 30 Oct 2024, 15:02 codecov[bot], ***@***.***> wrote:

> Codecov
> <https://app.codecov.io/gh/talgalili/dendextend/pull/130?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tal+Galili>
> Report
>
> All modified and coverable lines are covered by tests ✅
>
> Project coverage is 43.13%. Comparing base (c1c132f)
> <https://app.codecov.io/gh/talgalili/dendextend/commit/c1c132f60750bb8f20b867ba02fe04050e58230f?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tal+Galili>
> to head (41646fb)
> <https://app.codecov.io/gh/talgalili/dendextend/commit/41646fb88817d7bd314d1413bb8591bc7685fede?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tal+Galili>
> .
>
> Additional details and impacted files
>
> @@            Coverage Diff             @@##           master     #130      +/-   ##
> ==========================================+ Coverage   42.46%   43.13%   +0.66%
> ==========================================
>   Files          50       50
>   Lines        4182     4182
> ==========================================+ Hits         1776     1804      +28     + Misses       2406     2378      -28
>
> ☔ View full report in Codecov by Sentry
> <https://app.codecov.io/gh/talgalili/dendextend/pull/130?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tal+Galili>
> .
> 📢 Have feedback on the report? Share it here
> <https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tal+Galili>
> .
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/talgalili/dendextend/pull/130#issuecomment-2448104167>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHOJBVMP5XNZDEM5BCKYTLZ6EUKXAVCNFSM6AAAAABQ4Y4O2KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINBYGEYDIMJWG4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-10-31 03:16 UTC, talgalili commented
I suggest to not work on `unloadNamespace` and the code there. I'd suggest keep it to the end of the work.
It's best to focus on testing core functions.

2024-10-31 12:53 UTC, alecbuetow commented
Sounds good, done playing with it

2024-10-31 13:02 UTC, talgalili commented
Cool. Please let me know once I can review this PR

On Thu, 31 Oct 2024, 14:53 Alec Buetow, ***@***.***> wrote:

> Sounds good, done playing with it
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/talgalili/dendextend/pull/130#issuecomment-2449775296>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHOJBWNKMSNTRDG2H67ZQDZ6IR6BAVCNFSM6AAAAABQ4Y4O2KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINBZG43TKMRZGY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-10-31 13:05 UTC, talgalili requested changes

2024-10-31 13:05 UTC, talgalili commented on R/ggdend.R
Why did you make this change? i believe it will break things.

2024-10-31 13:30 UTC, alecbuetow commented on R/ggdend.R
I was getting the following warning, which was resolved when `size` was switched to `linewidth`. You're right though, size = 1 and linewidth = 1 won't set the line to the same width. Better to go with the old version

Warning (test-ggdend.R:151:4): ggplot doesn't have warnings for dendrograms
Using `size` aesthetic for lines was deprecated in ggplot2
3.4.0.
ℹ Please use `linewidth` instead.
Backtrace:
    ▆
 1. ├─ggplot2::ggplot(as.dendrogram(hclust(dist(mtcars)))) at test-ggdend.R:151:4
 2. └─dendextend:::ggplot.dendrogram(as.dendrogram(hclust(dist(mtcars))))
 3.  ├─ggplot2::ggplot(as.ggdend(data), ...) at dendextend/R/ggdend.R:635:3
 4.  └─dendextend:::ggplot.ggdend(as.ggdend(data), ...)
 5.    └─ggplot2::geom_segment(...) at dendextend/R/ggdend.R:537:6
 6.      └─ggplot2::layer(...)
 7.        └─ggplot2:::deprecate_soft0(...)

2024-10-31 14:48 UTC, merged

2024-10-31 14:49 UTC, talgalili commented
Thanks, merged.

Keep them coming :)


Regarding the size vs linewidth, maybe open an issue on this so we won't forget to find a solution for this in the future?
Thanks!